### ISSUE TITLE
Validation fails on unsupported intrinsic function

### ISSUE THREAD

**Issue by mikecbrant** [martysweet/cfn-lint#102]
First off, thanks for work on this library, I have been pretty happy in exploring its use within my toolchain.  I am wondering if you have given consideration to having known unsupported functionality (i.e. for Fn::Select) not be consider a critical (perhaps optionally).  I would think more desirable behavior would be to warn on unsupported function, such that an otherwise valid template does not fail validation.

An example use case that brought this to my attention:

```
  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [ 0, !GetAZs '']
```
