### ISSUE TITLE
Validation error for 'null' values

### ISSUE THREAD

**Issue by RazzM13** [martysweet/cfn-lint#123]
Apparently, when `cfn-lint` encounters a `null` value in a template, it is unable to process it and throws an exception.

Steps to reproduce:
1) Create a `test.yaml` file that triggers a `null` value exception, perhaps with the following contents:
```
Resources:
  MyBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      Tags: null
```
2) Attempt to validate the file:
`cfn-lint validate test.yaml`
3) Observe the output:
[validate.log](https://github.com/martysweet/cfn-lint/files/1855988/validate.log)

Expected: Processing to continue and a standard validation error to be displayed at the end.
Actual: An exceptions is logged `... uncaughtException: Cannot convert undefined or null to object ...` and processing stops.
