### ISSUE TITLE
Fn::Select doesn't understand default parameter list

### ISSUE THREAD

**Issue by jamielennox** [martysweet/cfn-lint#138]
When defining a default value for a Parameter as a list you define values as a comma seperated string. For example: 
```
Parameters:
  AvailabilityZones:
    Description: List of Availability Zones to use for the subnets in the VPC.
    Type: List<AWS::EC2::AvailabilityZone::Name>
    Default: ap-southeast-2a,ap-southeast-2b,ap-southeast-2c
```
Later on I use select on this list like so: 
```
  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref 'VPC'
      CidrBlock: !Ref 'PrivateSubnet1CIDR'
      AvailabilityZone: !Select
        - '0'
        - !Ref 'AvailabilityZones'
```
This all works great in practice, however cfn-list obviously looks at the default and doesn't know that that value is a list, not a string and so I get validation errors like: 
```
Resource: Resources > PrivateSubnet1 > Properties > AvailabilityZone
Message: Fn::Select requires the second element to be a list, function call did not resolve to a list. It contains value ap-southeast-2a,ap-southeast-2b,ap-southeast-2c
Documentation: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-select.html
```
