### ISSUE TITLE
Cloudfront DistribConfig - ARN validation failure on intrinsic functions

### ISSUE THREAD

**Issue by willgarcia** [martysweet/cfn-lint#143]
First of all, thanks for this tool 👍 

The following template:

```
Description: TEST
Parameters:
  ACMCertificateARN:
    Description: ARN for certificate to be used by CloudFront
    Type: String

Resources:
  DistributionConfig:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        ViewerCertificate:
          AcmCertificateArn: !Ref ACMCertificateARN
```

fails to validate:

```
0 warn
1 crit
Resource: Resources > DistributionConfig > Properties > DistributionConfig > ViewerCertificate > AcmCertificateArn
Message: Expecting an ARN, got 'string_input_ACMCertificateARN'
Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudfront-distribution.html

Template invalid!
```

And, replacing the Ref function that references a template parameter (`AcmCertificateArn: !Ref ACMCertificateARN`) by a string works.

At this stage, I'm unsure of the cause of this validation failure. I suspect that the `validator.isArn` function seems to expect a string starting with `arn:aws` as per https://github.com/martysweet/cfn-lint/blob/2e2a767d31b2b5bb7a529c43d6c32878f57443f1/src/validator.ts#L1436.
