### ISSUE TITLE
1.6.1 error on !GettAtt of Outputs - was passing with 1.6.0

### ISSUE THREAD

**Issue by gidbalugo** [martysweet/cfn-lint#149]
We recently failed on 1.6.1 update which produces error on `!GetAtt` Outputs of AWS::CloudFormation::Stack. This was passing on before the update of 1.6.1

Sample template code causing failed results on 1.6.1 update but with passing build with 1.6.0

Error

```
Running cfn-lint on bootstrap.yaml
0 infos
0 warn
1 crit
Resource: Outputs > InfrastructurePipelineUrl > Value
Message: No such attribute Outputs.PipelineUrl on AWS::CloudFormation::Stack
Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-stack.html

Template invalid!
Exited with code 1
```

The template(s) resulting to error(bootstrap.yaml)

 ```Resources:
  InfrastructurePipeline:
    Type: AWS::CloudFormation::Stack
    Properties:
      // rest of code here

Outputs:
  InfrastructurePipelineUrl:
    Description: The continuous deployment pipeline in the AWS Management Console.
    Value: !GetAtt InfrastructurePipeline.Outputs.PipelineUrl
```

The `Outputs` part of source template.

```
Outputs:
  PipelineUrl:
    Value: !Sub https://console.aws.amazon.com/codepipeline/home?region=${AWS::Region}#/view/${Pipeline}
```

Thanks

**Comment by RazzM13** [comment]
Apparently, the issue does not occur prior to 1b867f1f9570594f0be0b075c1db7ad8618d149f, perhaps @martysweet or @tomdionysus can help more...

FWIW, I've just tested with:
```
AWSTemplateFormatVersion: '2010-09-09'
Resources:
  InfrastructurePipeline:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: "https://s3.amazonaws.com/templates/myTemplate.template?versionId=123ab1cdeKdOW5IH4GAcYbEngcpTJTDW"
Outputs:
 InfrastructurePipelineUrl:
   Description: The continuous deployment pipeline in the AWS Management Console.
   Value: !GetAtt InfrastructurePipeline.Outputs.PipelineUrl
```
