### ISSUE TITLE
ARN validation failure on imported values

### ISSUE THREAD

**Issue by jonscheiding** [martysweet/cfn-lint#175]
I'm getting validation errors when trying to use `!ImportValue` for properties that expect an ARN.

Sample template:
```
Resources:
  DomainName:
    Type: AWS::ApiGateway::DomainName
    Properties:
      RegionalCertificateArn: !ImportValue ExportedRegionalCertificateArn
      DomainName: some.domain.com
      EndpointConfiguration:
        Types:
          - REGIONAL
```

I get the following result:
```
1 crit
Resource: Resources > DomainName > Properties > RegionalCertificateArn
Message: Expecting an ARN, got 'IMPORTEDVALUEExportedRegionalCertificateArn'
Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-domainname.html
```

I tried doing something similar with a different type of resource that also expects an ARN:

```
Resources:
  User:
    Type: "AWS::IAM::User"
    Properties: 
      ManagedPolicyArns:
        - !ImportValue ExportedManagedPolicyArn
      UserName: "someuser"
```

This passed, but it passes even if I put in a garbage non-ARN, so it doesn't appear to be doing the validation at all.

I am using `cfn-lint@1.7.2`.

Similar to #143, but so far I don't see a workaround.  I'm happy to work on a PR, if this is indeed erroneous behavior.

Thanks!
