### ISSUE TITLE
cfn-lint shows an error, but the CF YAML is good, and works

### ISSUE THREAD

**Issue by beginrescueend** [martysweet/cfn-lint#193]
For the following code, I get an error that should not be an issue (the PeerRoleArn is an actual ARN, with a type of string, and the code works) -

**Adapted From step 2 of this page**
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/peer-with-vpc-in-another-account.html

**Error message:**
```
Resource: Resources > vpcPeeringConnection > Properties > PeerRoleArn
Message: Expecting an ARN, got 'string_input_PeerRoleArn'
Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-vpcpeeringconnection.html
```

**Code:**

```
vpcPeeringConnection:
    Type: 'AWS::EC2::VPCPeeringConnection'
    Properties:
      VpcId: !Ref VPC
      PeerVpcId: !Ref myPeerVPC
      PeerOwnerId: !Ref myPeerAWSID
      PeerRoleArn: !Ref PeerRoleArn
```
