### ISSUE TITLE
False alert for *Arn parameters that Ref other resources

### ISSUE THREAD

**Issue by vivus-ignis** [martysweet/cfn-lint#212]
Hi!

I've just upgraded to 1.9.2 and now I'm having errors on otherwise valid templates. Example:

```yaml
  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Scheme: internal
<...>

  DevNullTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Port: 80
      Protocol: HTTP
<...>

  LoadBalancerHTTPListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - TargetGroupArn: !Ref DevNullTargetGroup
          Type: forward
      LoadBalancerArn: !Ref LoadBalancer
      Port: 80
      Protocol: HTTP

```

And here's what cfn-lint outputs:

```
Resource: Resources > LoadBalancerHTTPListener > Properties > DefaultActions > 0 > TargetGroupArn
Message: Expecting an ARN, got 'mock-ref-DevNullTargetGroup'
Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticloadbalancingv2-listener.html

Resource: Resources > LoadBalancerHTTPListener > Properties > LoadBalancerArn
Message: Expecting an ARN, got 'mock-ref-LoadBalancer'
Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticloadbalancingv2-listener.html
```

For ELBv2 load balancer & target group resources !Ref returns an Arn. 

Maybe there's a way to check when a !Ref for a given resource would return an Arn and then properly mock a string?

Thank you.
