### ISSUE TITLE
Fn::Split and Fn::Sub combination false positive

### ISSUE THREAD

**Issue by romaninsh** [martysweet/cfn-lint#221]
```
Resource: Resources > B3AdminIdentityPool > Properties > IdentityPoolName
Message: Fn::Split does not support function 'Fn::Sub' here
Documentation: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-split.html
```

code:

```
  B3AdminIdentityPool:
    Type: AWS::Cognito::IdentityPool
    Properties:
      IdentityPoolName: 
         Fn::Join: 
          - "_"
          - Fn::Split: 
            - "-"
            - !Sub ${Infra}-b3-admin
```

valid syntax replacing "-" with "_" in a string.
