### ISSUE TITLE
!Select and !Cidr

### ISSUE THREAD

**Issue by arpaulnet** [martysweet/cfn-lint#225]
Output:
```
0 infos
0 warn
2 crit
Resource: 
Message: Fn::Select does not support the Fn::Cidr function in argument 2
Documentation: http://docs.aws.amazon.com/search/doc-search.html?searchPath=documentation-guide&searchQuery=&x=0&y=0&this_doc_product=AWS+CloudFormation&this_doc_guide=User+Guide&doc_locale=en_us#facet_doc_product=AWS%20CloudFormation&facet_doc_guide=User%20Guide
```

Relevant Template Snippet:
```yaml
  PublicSubnet0:
    Type: AWS::EC2::Subnet
    DependsOn: VpcIpv6CidrBlock
    Properties:
      AvailabilityZone: !Ref AvailabilityZone0
      CidrBlock: !Ref PublicSubnetIpv4Cidr0
      Ipv6CidrBlock: !Select [0, "Fn::Cidr": [!Select [0, !GetAtt 'Vpc.Ipv6CidrBlocks'], 256, 64]]
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-pub-0"
      VpcId: !Ref Vpc
```
The series of functions in `Ipv6CidrBlock` works; I can deploy a stack and it produces the desired behavior.
