### ISSUE TITLE
Tags is not a valid property of AWS::AutoScaling::AutoScalingGroup

### ISSUE THREAD

**Issue by sjparkinson** [martysweet/cfn-lint#24]
[Yes it is](https://docs.aws.amazon.com/autoscaling/latest/userguide/autoscaling-tagging.html).

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-as-group.html#aws-properties-as-group-prop

For example:

```yaml
ConsulAutoScalingGroup:
  Type: AWS::AutoScaling::AutoScalingGroup
  Properties:
    DesiredCapacity: 3
    MaxSize: 7
    MinSize: 3
    MetricsCollection:
      Granularity: 1Minute
    HealthCheckType: EC2
    LaunchConfigurationName: !Ref ConsulLaunchConfiguration
    VPCZoneIdentifier: !FindInMap [!Ref "AWS::AccountId", !Ref "AWS::Region", "PrivateSubnets"]
    Tags:
      - Key: Consul-Auto-Discover
        Value: !Sub "Consul-${AWS::AccountId}-${AWS::Region}-${AWS::StackName}"
        PropagateAtLaunch: true
```
