### ISSUE TITLE
Tags is not a valid property of AWS::ECR::Repository

### ISSUE THREAD

**Issue by MatteoInfi** [martysweet/cfn-lint#241]
Not really sure what is wrong here

```
  ECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      Tags:
        - Key: app
          Value: !Ref Appname
        - Key: env
          Value: !Ref Environment
        - Key: type
          Value: storage
      RepositoryName: !Sub ${Appname}-${Environment}
      RepositoryPolicyText:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowPushPull
            Effect: Allow
            Principal:
              AWS:
                - !GetAtt BuildProject.Arn
            Action:
              - "ecr:GetDownloadUrlForLayer"
              - "ecr:BatchGetImage"
              - "ecr:BatchCheckLayerAvailability"
              - "ecr:PutImage"
              - "ecr:InitiateLayerUpload"
              - "ecr:UploadLayerPart"
              - "ecr:CompleteLayerUpload"

```

And I get this error:

```
Resource: Resources > ECRRepository > Properties > Tags
Message: Tags is not a valid property of AWS::ECR::Repository
Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecr-repository.html

```
