### ISSUE TITLE
Problem with AWS::IAM::Role with placement of Description

### ISSUE THREAD

**Issue by bensiu** [martysweet/cfn-lint#244]
Properly placed Description property in Properties when defined 'AWS::IAM::Role' is marked as error:

```
NameOfTheRole:
  Type: 'AWS::IAM:Role'
  Properties:
    RoleName: SomeName:
    Description: Your role description
```
