### ISSUE TITLE
Pass pseudo parameters as CLI arguments

### ISSUE THREAD

**Issue by sjparkinson** [martysweet/cfn-lint#25]
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/pseudo-parameter-reference.html

To avoid:

```
Resource: Resources > ConsulLoadBalancerSecurityGroup > Properties > VpcId
Message: Could not find value in map 123456789012|eu-west-1|VpcId. Have you tried specifying input parameters?
Documentation: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-base64.html
```

```yaml
'000000000000':
  eu-west-1:
    VpcId: vpc-00000000
```
