### ISSUE TITLE
ManagedPolicyName is not a valid property

### ISSUE THREAD

**Issue by martysweet** [martysweet/cfn-lint#42]
```
  DeploymentIAMPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: DeploymentPolicyForMyApplication
```

Results in:

```
1 crit
Resource: Resources > DeploymentIAMPolicy > Properties
Message: ManagedPolicyName is not a valid property of AWS::IAM::ManagedPolicy
Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-managedpolicy.html
```

However "ManagedPolicyName" is specified here http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-managedpolicy.html
