### ISSUE TITLE
Bucket Transitions non-array not detected

### ISSUE THREAD

**Issue by martysweet** [martysweet/cfn-lint#43]
```
  S3LoggingBucket:
    Type: AWS::S3::Bucket
    Properties:
      LifecycleConfiguration:
        Rules:
          - Status: Enabled
            Transitions:
                StorageClass: GLACIER
                TransitionInDays: 60
```

is Invalid as Transitions should be array types (http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket-lifecycleconfig-rule.html).

```
  S3LoggingBucket:
    Type: AWS::S3::Bucket
    Properties:
      LifecycleConfiguration:
        Rules:
          - Status: Enabled
            Transitions:
              - StorageClass: GLACIER
                TransitionInDays: 60
```

would be correct...
