### ISSUE TITLE
Validation on properties of a parameter

### ISSUE THREAD

**Issue by aarongorka** [martysweet/cfn-lint#59]
An invalid property on a parameter doesn't seem to trigger an error (there's a typo in the `Default` key):

```
Parameters:
  MyPassword:
    Description: Password
    Type: String
    Defaut: hunter2
    NoEcho: True
```

This parameter was used in some UserData via `Fn::Sub`.
