### ISSUE TITLE
Conditional properties failing to evaluate

### ISSUE THREAD

**Issue by aarongorka** [martysweet/cfn-lint#61]
I'm not sure if this is currently supported, but I have some conditionals that are empty after being evaluated:

```
Parameters:
  Env:
    Description: Which Environment
    Type: String
    Default: Dev
    AllowedValues:
      - Dev
      - QA
      - PreProd
      - Production

Conditions:
  isProd: !Equals [!Ref Env, Production]
  isPreProd: !Equals [!Ref Env, PreProd]
  isProdOrPreProd: !Or
    - Condition: isProd
    - Condition: isPreProd
  isNotProdOrPreProd: !Not
    - Condition: isProdOrPreProd

Mappings:
  App:
    Dev:
      CertificateId: NA
      CertificateArn: arn:aws:acm:us-east-1:etc
    Production:
      CertificateId: 09187234234
      CertificateArn: NA

# ... CloudFront config
        ViewerCertificate:
          IamCertificateId: !If
             - isProd
             - !FindInMap [App, !Ref Env, CertificateId]
             - !Ref "AWS::NoValue"
          AcmCertificateArn: !If
             - isPreProd
             - !FindInMap [App, !Ref Env, CertificateArn]
             - !Ref "AWS::NoValue"
```

`cfn-lint validate myapp.yml --pseudo AWS::Region=ap-southeast-2`

Results in:

```
3 crit
Resource: Resources > cloudfrontDistribution > Properties > DistributionConfig > ViewerCertificate > IamCertificateId
Message: Expected type String for IamCertificateId, got value '' instead
Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-distributionconfig-viewercertificate.html#cfn-cloudfront-distributionconfig-viewercertificate-iamcertificateid

Resource: Resources > cloudfrontDistribution > Properties > DistributionConfig > ViewerCertificate > AcmCertificateArn
Message: AcmCertificateArn is expecting an Arn, '' given. If this is a parameter, has it been specified with --parameters?
Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-distributionconfig-viewercertificate.html#cfn-cloudfront-distributionconfig-viewercertificate-acmcertificatearn

Resource: Resources > cloudfrontDistribution > Properties > DistributionConfig > ViewerCertificate > AcmCertificateArn
Message: Expected type String for AcmCertificateArn, got value '' instead
Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-distributionconfig-viewercertificate.html#cfn-cloudfront-distributionconfig-viewercertificate-acmcertificatearn
```
