### ISSUE TITLE
Exception when passing an AWS::ECS::TaskDefinition with LogConfiguration

### ISSUE THREAD

**Issue by akdor1154** [martysweet/cfn-lint#69]
task.yaml:
```yaml
Resources:
  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ContainerDefinitions:
        - LogConfiguration:
            Options:
              awslogs-region: "region"
```
`cfn-lint validate task.yaml`
```
/usr/local/lib/node_modules/cfn-lint/lib/resourcesSpec.js:121
    return spec.hasOwnProperty('AdditionalProperties') && spec['AdditionalProperties'] === true;
               ^

TypeError: Cannot read property 'hasOwnProperty' of null
    at Object.isAdditionalPropertiesEnabled (/usr/local/lib/node_modules/cfn-lint/lib/resourcesSpec.js:122:16)
    at checkResourceProperty (/usr/local/lib/node_modules/cfn-lint/lib/validator.js:928:49)
    at checkProperty (/usr/local/lib/node_modules/cfn-lint/lib/validator.js:1049:21)
    at checkResourceProperty (/usr/local/lib/node_modules/cfn-lint/lib/validator.js:973:17)
    at checkProperty (/usr/local/lib/node_modules/cfn-lint/lib/validator.js:1049:21)
    at checkResourceProperty (/usr/local/lib/node_modules/cfn-lint/lib/validator.js:973:17)
    at checkProperty (/usr/local/lib/node_modules/cfn-lint/lib/validator.js:1049:21)
    at checkResourceProperty (/usr/local/lib/node_modules/cfn-lint/lib/validator.js:955:29)
    at /usr/local/lib/node_modules/cfn-lint/lib/validator.js:919:9
    at Array.forEach (native)
```
