### ISSUE TITLE
API Gateway Support

### ISSUE THREAD

**Issue by concon121** [martysweet/cfn-lint#81]
We're getting a bunch of critical issues on our API Gateway definitions, which we believe are not actually issues.

They are mostly variations on these 3 issues:

*API Gateway Resource PathPart*
Resource: Resources > APIGatewayResource > Properties > PathPart
Message: Expected type String for PathPart, got value '{myPathPart}'

*API Gateway Integration Responses*
Resource: Resources > APIGatewayGetMethod > Properties > Integration > application/json
Message: Expected type String for application/json, got value '#set($inputRoot = $input.path('$'))

*API Gateway Selection Pattern*
Resource: Resources > APIGatewayGetMethod > Properties > Integration > SelectionPattern
Message: Expected type String for SelectionPattern, got value '.*InternalServerError.*'

This is a snippet of the offending cfn:

```
    APIGatewayResource:
      Type: "AWS::ApiGateway::Resource"
      Properties:
        PathPart: "{myPathPart}"
        RestApiId:
          Ref: APIGateway
    APIGatewayGetMethod:
      Type: "AWS::ApiGateway::Method"
      Properties:
        ApiKeyRequired: false
        AuthorizationType: "NONE"
        HttpMethod: GET
        Integration:
          Type: "AWS"
          PassthroughBehavior: WHEN_NO_TEMPLATES
          IntegrationHttpMethod: POST
          IntegrationResponses:
            - StatusCode: 200
            - StatusCode: 500
              ResponseTemplates:
                application/json:
                  Fn::FindInMap: [CustomVariables, responseTemplates, error]
              SelectionPattern: .*InternalServerError.*
            - StatusCode: 400
              SelectionPattern: .*BadRequest.*
              ResponseTemplates:
                application/json:
                  Fn::FindInMap: [CustomVariables, responseTemplates, error]
            - StatusCode: 404
              SelectionPattern: .*NotFound.*
              ResponseTemplates:
                application/json:
                  Fn::FindInMap: [CustomVariables, responseTemplates, error]
          RequestTemplates:
            application/json:
              Fn::FindInMap: [CustomVariables, requestTemplates, valid]
          Uri:
            Fn::Sub:
              - "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${Lambda}/invocations"
              - Lambda:
                  Fn::GetAtt: [LambdaFunction, Arn]
        MethodResponses:
          - StatusCode: 200
            ResponseModels:
              application/json:
                Ref: ResponseModel
          - StatusCode: 500
          - StatusCode: 400
          - StatusCode: 404
        ResourceId:
          Ref: APIGatewayResource
        RestApiId:
          Ref: APIGateway
```
